
= Einleitung

Modelica ist eine objektorientierte Programmiersprache zur Entwicklung komplexer dynamischer Diagramme, die graphisch dargestellt und bearbeitet werden können.

Zum Erstellen und Bearbeiten dieser Diagramme gibt es verschiedene Tools, wie zum Beispiel OMEdit. OMEdit ist für Hochschulen besonders interessant, da es der einzige Open-Source-Editor für Modelica ist. Allerdings kann OMEdit viel mehr als nur Diagramme erstellen (mehr dazu in Kapitel xx), was das Programm langsam und gerade für Anfänger sehr unübersichtlich macht. Leider enthält OMEdit auch einige Bugs, die es manchmal nötig machen, Dinge direkt im Code anzupassen. Hierbei ist nicht ersichtlich in welchen Fällen der Editor funktioniert und wann eine manuelle Anpassung erforderlich ist. Außerdem ist die Bedienung von OMEdit sehr unintuitiv und an vielen Stellen sehr umständlich.

Da aber ein Modelica-Editor für die Lehre benötigt wird, wird in dieser Arbeit ein Diagramm-Editor (MoDE) entwickelt, der nur die nötigsten Funktionen bereitstellt und eine möglichst intuitive Benutzeroberfläche hat. Hierdurch soll den Studenten der Einstieg in Modelica erleichtert werden.

== Aufgabenstellung


== Aufbau der Arbeit

Im nächsten Kapitel wird der Open-Source Modelica-Editor OMEdit vorgestellt. Danach werden einige Grundlagen kurz erläutert (Kapitel 3). Anschließend werden in Kapitel 4 einige Aspekte der Implementierung diskutiert. In Kapitel 5 wird der, im Rahmen dieser Arbeit, entwickelte Modelica-Editor vorgestellt. Zum Schluss kommt ein kurzes Fazit und ein Ausblick auf mögliche weiterführende Arbeiten.
