
= [[einleitung]] Einleitung

Modelica ist eine objektorientierte Programmiersprache zur Entwicklung komplexer dynamischer Diagramme, die graphisch dargestellt und bearbeitet werden können. <<4>>

Zum Erstellen und Bearbeiten dieser Diagramme gibt es verschiedene Tools, wie zum Beispiel OMEdit. OMEdit ist für Hochschulen besonders interessant, da es der einzige Open-Source-Editor für Modelica ist. Allerdings kann OMEdit viel mehr als nur Diagramme erstellen (mehr dazu in Kapitel <<omedit, 2.1>>), was das Programm langsam und gerade für Anfänger sehr unübersichtlich macht. Leider enthält OMEdit auch einige Bugs, die es manchmal nötig machen, Dinge direkt im Code anzupassen. Hierbei ist nicht ersichtlich in welchen Fällen der Editor funktioniert und wann eine manuelle Anpassung erforderlich ist. Außerdem ist die Bedienung von OMEdit sehr unintuitiv und an vielen Stellen sehr umständlich. <<6>>

Da aber ein Modelica-Editor für die Lehre benötigt wird, wird in dieser Arbeit ein Diagramm-Editor (MoDE) entwickelt, der nur die nötigsten Funktionen bereitstellt und eine möglichst intuitive Benutzeroberfläche hat. Hierdurch soll den Studenten der Einstieg in Modelica erleichtert werden.

== [[aufgabenstellung]] Aufgabenstellung

Wie in Kapitel <<einleitung, 1>> bereits erwähnt, wird in dieser Arbeit ein Diagramm-Editor für Modelica entwickelt.

Als Minimalanforderung für den Editor sind diese Funktionen vorgesehen:

Der Editor ...

* kann Modelica-Libraries laden und als Baum darstellen.
* kann die Icons von geladenen Modelica-Modellen als Vektorgrafik darstellen.
* kann geladene Modelle zu einem neuen Modell hinzufügen und in diesem frei positionieren.
* kann die Diagramm-Ansicht von bestehenden Modellen laden (Modelle + Linien + Konnektoren) und auch in dieser Untermodelle verschieben.
* kann Gleichungen hinzufügen und entsprechende Linien zwischen Modellen zeichnen.
* kann zusammengesetzte Modelle speichern.

////
Des weiteren sind für den Editor diese wünschenwerten Anforderungen geplant:

Der Editor ...
* unterstützt unterschiedliche Strategien zum zeichnen von Linien.
* erlaubt es Linienpunkte manuell zu verschieben.
* kann anzeigen, ob eine gewünschte Verbindung semantisch korrekt ist (kompatible Konnektortypen).
* aktualisiert Konnektorlinien beim Verschieben von Komponenten.
kann alle Linien eines Diagramms planar machen.
kann Modellkomponenten vergrößern/verkleinern/rotieren.
kann Templateausdrücke in Annotationstexten ersetzen (%name%, etc.).
////

== Aufbau der Arbeit

Im nächsten <<omedit, Kapitel>> wird der Open-Source Modelica-Editor OMEdit vorgestellt. Danach werden einige Grundlagen kurz erläutert (Kapitel <<grundlagen, 3>>). Anschließend werden in Kapitel <<umsetzung, 4>> einige Aspekte der Implementierung diskutiert. In Kapitel <<ergebnisse, 5>> wird der, im Rahmen dieser Arbeit, entwickelte Modelica-Editor vorgestellt. Zum Schluss kommt ein kurzes Fazit und ein Ausblick auf mögliche weiterführende Arbeiten (Kapitel <<fazit, 6>>).
